# application.yml

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microco
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  #logging:
 # level:
 #   root: INFO
  #  com.example: DEBUG

